# The following lines were added by compinstall
zstyle :compinstall filename '/Users/treytomlinson/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

#
# the main RC file (will be linked to ~/.zshrc)
#

# ---------- #
# zsh config #
# ---------- #

#
# build array of environment config files for sourcing
#

typeset -ga sources
sources+="$HOME/projects/dotfiles/zsh/antigenrc.zsh"
sources+="$HOME/projects/dotfiles/zsh/functions.zsh"
sources+="$HOME/projects/dotfiles/zsh/aliases.zsh"
sources+="$HOME/projects/dotfiles/zsh/prompt.zsh"

#
# include sources
#

foreach file (`echo $sources`)
    if [[ -a $file ]]; then
        source $file
    fi
end

#
# custom bin directory for scripting
#

# export PATH="$HOME/projects/dotfiles/bin:$PATH"

# ----- #
# rbenv #
# ----- #

# export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi


# ------- #
# python3 #
# ------- #

export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PATH="$HOME/Library/Python/3.7/bin:$PATH"

# ------ #
# golang #
# ------ #

# export GOPATH=$HOME/projects/go-workspace
# export GOROOT=/usr/local/opt/go/libexec
# export PATH=$PATH:$GOPATH/bin
# export PATH=$PATH:$GOROOT/bin

# ---- #
# node #
# ---- #

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion


# ------- #
# ansible #
# ------- #

# workaround for Ansible fork() issue on macOS Mojave
export OBJC_DISABLE_INITIALIZE_FORK_SAFETY=YES


# ------ #
# direnv #
# ------ #

eval "$(direnv hook zsh)"


# --- #
# hub #
# --- #

eval "$(hub alias -s)"