# Lines configured by zsh-newuser-install
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/Users/trey/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

##Load Powerline
source /usr/local/lib/python2.7/site-packages/powerline/bindings/zsh/powerline.zsh


# ----- #
# rbenv #
# ----- #

export PATH="$HOME/.rbenv/bin:$PATH"

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi


# --- #
# hub #
# --- #

eval "$(hub alias -s)"

# ------- #
# aliases #
# ------- #

alias todo="subl ~/Documents/todo.txt"

alias dotf="subl ~/.dotfiles"


alias git="hub"
alias gs="git status"
alias gds="git diff | subl"
alias gc="git checkout"
alias ga="git add ."
alias gb='git branch -av'

alias gpu="git push --set-upstream origin HEAD"

alias gcb="git checkout -b"

#removes all local branches that have been merged into master
alias gclean="git branch --merged master | ag -v '\* master' | xargs -n 1 git branch -d"

# # Log (l)
# print contributors by # of commits
alias glc="git shortlog --summary --numbered"
#detailed log
alias gl="git log --all --graph --decorate"
#prettylog
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
#shortlog
alias gls='git log --topo-order --all --graph --pretty=format:"${_git_log_oneline_format}"'

# # Remote (r)
alias grl="git remote --verbose"
alias gra="git remote add"


# git commit / twitter
# function gcm {
#   git commit -m "$1"
#   ruby -e 'require %(jumpstart_auth);ARGV.join(" ").scan(/.{1,140}/).each { |tweet| JumpstartAuth.twitter.update(tweet)}' $1
# }


alias s="subl"
alias ss="subl ."


##
# navigation #
alias ..="cd .."
alias tu1="cd ~/turing/module1"
alias tu2="cd ~/turing/module2"

# alias l='ls -1A'         # Lists in one column, hidden files.
# alias ll='ls -lh'        # Lists human readable sizes.
# alias lr='ll -R'         # Lists human readable sizes, recursively.
# alias la='ll -A'         # Lists human readable sizes, hidden files.
# alias lm='la | "$PAGER"' # Lists human readable sizes, hidden files through pager.
# alias lx='ll -XB'        # Lists sorted by extension (GNU only).
# alias lk='ll -Sr'        # Lists sorted by size, largest last.
# alias lt='ll -tr'        # Lists sorted by date, most recent last.
# alias lc='lt -c'         # Lists sorted by date, most recent last, shows change time.
# alias lu='lt -u'         # Lists sorted by date, most recent last, shows access time.
# alias sl='ls'            # I often screw this up.


# Resource Usage
# alias df='df -kh'

#display path for troubleshooting
alias path="echo '$PATH' | tr : '\n'"


# ------------- #
# miscellaneous #
# ------------- #

# Get week number #
alias week='date +%V'

