# The following lines were added by compinstall
zstyle :compinstall filename '$HOME/.zshrc'

autoload -Uz compinit
compinit

# ---------- #
# zsh config #
# ---------- #

#
# build array of environment config files for sourcing
#

typeset -ga sources
sources+="$HOME/projects/dotfiles/zsh/antigenrc.zsh"
sources+="$HOME/projects/dotfiles/zsh/functions.zsh"
sources+="$HOME/projects/dotfiles/zsh/aliases.zsh"
sources+="$HOME/projects/dotfiles/zsh/prompt.zsh"

#
# include sources
#

foreach file (`echo $sources`)
    if [[ -a $file ]]; then
        source $file
    fi
end

#
# custom dir for scripting
#

# export PATH="$HOME/projects/dotfiles/bin:$PATH"

# ------- #
# python3 #
# ------- #

export PATH="/usr/local/opt/python/libexec/bin:$PATH"
export PATH="$HOME/Library/Python/3.7/bin:$PATH"
